default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: airbnb_clone_development
  username: airbnb_clone
  password: 1234
  host: localhost
  port: 5432

test:
  <<: *default
  database: airbnb_clone_test
  username: airbnb_clone
  password: 1234
  host: localhost
  port: 5432

production:
  <<: *default
  database: airbnb_clone_production
  username: airbnb_clone
  password: <%= ENV["AIRBNB_CLONE_DATABASE_PASSWORD"] %>
